test_auc_reflag(two_uniques) (__main__.GrouperTest) ... test_genemap(two_uniques) (__main__.GrouperTest) ... ok
test_redundant_peaks(two_uniques) (__main__.GrouperTest) ... test_seqlower(two_uniques) (__main__.GrouperTest) ... ok
test_seqmodi(two_uniques) (__main__.GrouperTest) ... ok
test_sequence_area(two_uniques) (__main__.GrouperTest) ... ok
test_split_on_geneid(two_uniques) (__main__.GrouperTest) ... FAIL

======================================================================
FAIL: test_auc_reflag(two_uniques) (__main__.GrouperTest) (calc=1.0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\parameterized_test.py", line 282, in auc_reflagAssert
    'result index {}').format(ix1, ix2))
AssertionError: 1.0 != 0 : Error in AUC Reflagger at input index 20, result index 20

======================================================================
FAIL: test_auc_reflag(two_uniques) (__main__.GrouperTest) (calc=1.0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\parameterized_test.py", line 282, in auc_reflagAssert
    'result index {}').format(ix1, ix2))
AssertionError: 1.0 != 0 : Error in AUC Reflagger at input index 66, result index 66

======================================================================
FAIL: test_redundant_peaks(two_uniques) (__main__.GrouperTest) (calc=0.0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\parameterized_test.py", line 247, in redundant_peakAssert
    'result index {}').format(ix1, ix2))
AssertionError: 0.0 != 1 : Error in Peak UseFlag at input index 19, result index 19

======================================================================
FAIL: test_redundant_peaks(two_uniques) (__main__.GrouperTest) (calc=1.0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\parameterized_test.py", line 247, in redundant_peakAssert
    'result index {}').format(ix1, ix2))
AssertionError: 1.0 != 0 : Error in Peak UseFlag at input index 20, result index 20

======================================================================
FAIL: test_split_on_geneid(two_uniques) (__main__.GrouperTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\parameterized_test.py", line 349, in test_split_on_geneid
    self.split_on_geneid()
  File ".\parameterized_test.py", line 299, in split_on_geneid
    self.assertEqual(len(usrdata), len(self.postsplit))
AssertionError: 141 != 104

----------------------------------------------------------------------
Ran 7 tests in 0.244s

FAILED (failures=5)
